stages:
- name: Build & Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: cod-api:${CICD_EXECUTION_SEQUENCE}
  when:
    branch: {}
    event:
      include:
      - push
      - pull request
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./cod-dc.yaml
  when:
    branch: {}
    event:
      include:
      - push
      - pull request
branch:
  include:
  - main
notification: {}
