apiVersion: apps/v1
kind: Deployment
metadata:
  name: cod-api
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cod
  template:
    metadata:
      labels:
        app: cod
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: cod
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: Always
        env:
        - name: BASE_URL
          valueFrom:
            secretKeyRef:
              key: BASE_URL
              name: call-of-duty
        - name: COD
          valueFrom:
            secretKeyRef:
              key: COD
              name: call-of-duty
        - name: CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              key: CONSUMER_KEY
              name: call-of-duty
        - name: CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              key: CONSUMER_SECRET
              name: call-of-duty
        - name: EMAIL
          valueFrom:
            secretKeyRef:
              key: EMAIL
              name: call-of-duty
        - name: KEY
          valueFrom:
            secretKeyRef:
              key: KEY
              name: call-of-duty
        - name: SECRET
          valueFrom:
            secretKeyRef:
              key: SECRET
              name: call-of-duty
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              key: REDIS_PASS
              name: redis-pass
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              key: REDIS_HOST
              name: redis-pass